#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cotillo_ShoppingCart_Android.Resource", IsApplication=true)]

namespace Cotillo_ShoppingCart_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Cotillo_ShoppingCart_Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Cotillo_ShoppingCart_Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Cotillo_ShoppingCart_Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int facebook_login = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_account_circle_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_shopping_cart_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_barcode_money_sales_sale = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_barcode_white = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_home_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_payment_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_search_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_shopping_cart_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_vpn_key_black_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_vpn_key_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int login_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int register_button = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int action_add = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int action_home = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int action_login = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int action_search = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int contentFrame = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int facebook_image = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int login_image = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int product_description = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int product_expiration_date = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int product_price_excl_tax = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int product_price_incl_tax = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int product_title = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int register_image = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Checkout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreditCardInfo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ManageProducts = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyAccount = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProcessPayment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Register = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ScanItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ShoppingCart = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int Actions = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AdminActions = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int CheckoutActions = 2131034114;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
